spring:
  application:
    name: my-web

  redis:
    host: 106.55.60.108 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

  mvc:
    view:
      prefix: /     #视图前缀
      suffix: .jsp  #视图后缀

  datasource:
    url: jdbc:mysql://106.55.60.108:3306/k_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: cjy92/mm
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: ${spring.application.name}-DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  main:
    lazy-initialization: false


management:
  endpoints:
    web:
      exposure:
        include: 'startup'
